### ISSUE TITLE
Static: avoid downloading `remote_file` at each run?

### ISSUE THREAD

**Issue by giorgian** [poise/poise-languages#2] opened 2015-10-26 15:15 UTC
At the end of installation, the tarball is deleted, and `remote_file` is unconditioned; this means the tarball gets downloaded at every run.

The best solution would IMO be to skip the download if the executable is there (for instance, in the case of javascript that would be `javascript_binary`; but it seems that the static resource doesn't now that. 

So, my suggestion would be to either have resources that depend on `PoiseLanguages::Static` provide the executable's relative path so that `PoiseLanguages::Static` can check if it's already there and skip download, or—a bit hackish, but still effective—just check that the destination path exists and is not empty.

**Comment by coderanger** [comment] 2015-10-26 17:25
As of more recent Chef releases, remote file supports ETags and If-Modified-Since. Are you seeing these not activate?

**Comment by coderanger** [comment] 2016-03-15 03:12
Closing this out as cannot reproduce.

**Closed** 2017-04-30 06:52 UTC
